pushroulette:
  users:
    Matt Carrier:
      genre: Rap
    Ben Sawyer:
      genre: Country
    Bill Campbell:
      genre: Electronic
    DJ Watson:
      genre: Classical
    Jon Burgess:
      genre: Holiday
    Kristin Jackvony:
      genre: Reggaeton
    Senior Nelson:
      genre: Latin
    Eric Bernier:
      genre: Disco
    Wade Leveille:
      genre: Piano
  github:
    users:
      mcarrierastonish: Matt Carrier
      bsawyer: Ben Sawyer
      campbill: Bill Campbell
      djwatson82: DJ Watson
      jonfromri: Jon Burgess
      kjackvony: Kristin Jackvony
      mnelson1: Senior Nelson
      wadeleveille: Wade Leveille
      ericmbernier: Eric Bernier
  buildServer:
    users:
      mcarrier: Matt Carrier
      mcarrieruri: Matt Carrier
      jschaeffer: Josh Schaeffer
      hzhu: Hongwei Zhu
      bsawyer: Ben Sawyer
      bcampbell: Bill Campbell
      dwatson: DJ Watson
      dpavao: Derek Pavao
      kjackvony: Kristin Jackvony
      kbober: Kyle Bober
      pderoxas: Paolo De Roxas
      wade.leveille.jr: Wade Leveille
      ebernier: Eric Bernier
    failureClip:
      # - 'your-shit-broken'
      - 'fail-trombone'
      # - 'fail-buzzer'
    backToNormalClip:
      - 'tada'
  hipchat:
    token: yourtoken
    username: Push Roulette
    room: pushroulette
