pushroulette:
  users:
    Matt Carrier:
      genre: Rap
    Josh Schaeffer:
      genre: Audiobooks
    Hongwei Zhu:
      genre: Metal
    Ben Sawyer:
      genre: Country
    Bill Campbell:
      genre: Comedy
    DJ Watson:
      genre: Classical
    Jon Burgess:
      genre: Holiday
    Kristin Jackvony:
      genre: Religion
    Kyle Bober:
      genre: Holiday
    Senior Nelson:
      genre: Latin
    Eric Bernier:
      genre: Folk
    Wade Leveille:
      genre: Piano
  github:
    users:
      mcarrierastonish: Matt Carrier
      joshschaeffer: Josh Schaeffer
      hzhu-astonish: Hongwei Zhu
      bsawyer: Ben Sawyer
      campbill: Bill Campbell
      djwatson82: DJ Watson
      dotDeeka: Derek Pavao
      jonfromri: Jon Burgess
      kjackvony: Kristin Jackvony
      kylebober: Kyle Bober
      mnelson1: Senior Nelson
      pderoxas: Paolo De Roxas
      wadeleveille: Wade Leveille
      ericmbernier: Eric Bernier
  buildServer:
    users:
      mcarrier: Matt Carrier
      mcarrieruri: Matt Carrier
      jschaeffer: Josh Schaeffer
      hzhu: Hongwei Zhu
      bsawyer: Ben Sawyer
      bcampbell: Bill Campbell
      dwatson: DJ Watson
      dpavao: Derek Pavao
      kjackvony: Kristin Jackvony
      kbober: Kyle Bober
      pderoxas: Paolo De Roxas
      wade.leveille.jr: Wade Leveille
      ebernier: Eric Bernier
    failureClip:
      # - 'your-shit-broken'
      - 'fail-trombone'
      # - 'fail-buzzer'
    backToNormalClip:
      - 'tada'
